spring:
  application:
    name: gi-source

  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false

  cloud.stream:
    bindings.output:
      destination: greetings
      content-type: application/json

server:
  port: 8888
management:
  port: 8889
  context-path: /manage

security:
  basic.path: ${management.context-path}/**
  user: # Override credentials in production.
    name: admin
    password: secret

logging.level:
  net.robi42.gisource: DEBUG
