spring:
  application.name: gi-source
  output.ansi.enabled: always

  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false

  cloud.stream:
    bindings.output:
      group: gi
      destination: greetings
      content-type: application/json

server:
  port: -1 # Not required.
management:
  port: 8889
  context-path: /manage

security:
  basic.path: ${management.context-path}/**
  user: # Override credentials in production.
    name: admin
    password: secret

logging.level:
  net.robi42.gisource: DEBUG
